---
# tasks file for JacksonCampolattaro.zsh

- name: Update git
  package:
      name: git 
      state: latest
  become: yes

- name: Install ZSH
  package:
      name: zsh 
      state: latest
  become: yes

- name: Set zsh as default shell
  user:
      name: "{{ ansible_user_id }}"
      shell: /bin/zsh
  become: yes

- name: Download oh-my-zsh
  get_url:
      url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh          
      dest: /tmp/install-oh-my-zsh.sh
      mode: 0755 # Makes retrieved files executable

- name: Install oh-my-zsh 
  command: 
      cmd: zsh /tmp/install-oh-my-zsh.sh
      creates: ~/.oh-my-zsh

- name: Retrieve zsh configuration files using git
  git:
      repo: https://github.com/JacksonCampolattaro/dotfiles-zsh.git
      dest: ~/.config/zsh
      depth: 1
      update: true

- name: Get a list of all the files in ~/.config/zsh
  find:
      paths: ~/.config/zsh
      hidden: true
  register: zsh_dotfiles

- name: Create symlinks for all the files found
  file:
      src: "{{ item.path }}"
      dest: ~/{{ item.path | basename }}
      force: true
      state: link
  with_items: "{{ zsh_dotfiles.files }}"

- name: Install powerlevel10K
  git:
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: "{{ ansible.env.ZSH_CUSTOM }}/themes/powerlevel10k"
      depth: 1
      update: true

- name: Install zsh syntax highlighting
  git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: "{{ ansible.env.ZSH_CUSTOM }}/plugins/zsh-syntax-highlighting"
      depth: 1
      update: true

      # - name: Place zshrc in home directory
      #   copy: 
      #         src: zshrc
      #         dest: ~/.zshrc  
      # 
      # - name: Install zsh-syntax-highlighting
      #   git:
      #           repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      #           dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
